[package]
name = "mindtrails_backend"
version = "0.0.0"
edition = "2021"

[dependencies]
axum = { git = "https://github.com/tokio-rs/axum" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
